[package]
name = "ghs"
version = "0.1.0"
authors = ["Vaibhav Kurhe <mcs192572@cse.iitd.ac.in>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
petgraph = "0.5.0"
